### ISSUE TITLE
Support for @react-three/xr

### ISSUE THREAD

**Issue by laffan** [JMBeresford/r3f-form#13]
**Is your feature request related to a problem? Please describe.**
Nope, not a problem. This library looks great.  I would just love to use this package in an XR project I'm working on, and it seems like making that a part of the product would be in line with the thrust of work thus far. (If I was handier with TypeScript I would try and make a PR, but sadly ...)

**Describe the solution you'd like**
When you point your VR controller at a text field and click, the field gains focus. When you click away, it loses focus.  Basically just letting your tool play nicely with `<Interactive />`  in @react-three/xr.  Because R3F's out-of-the-box solution for rendering DOM content [doesn't work in XR](https://github.com/pmndrs/react-xr/issues/21), and troika-3d-text is overwhelmingly the best text rendering solution right now, my guess is that I'm not the only one looking for this exact thing.

**Describe alternatives you've considered**
There really aren't any. (And I have looked.) The folks over at https://github.com/musehq/spacesvr have something that looks like it might work, but it's bound to their (very specific) use case.

**Additional context**
Thanks for making r3f-form!

**Comment by JMBeresford** [comment]
Thanks for the feedback and the kind words!

With respect to the functionality you described, I believe this is currently already possible by using the `<Input />`s ref. Note that the ref passed to `<Input ref={ref} />` (or similarly, to <Textarea ref={ref} />) will be forwarded to the actual DOM element rather than anything in the 3D scene.

It seems like the [<Interactive />](https://github.com/pmndrs/react-xr#interactive) wrapper is just binding a handful of events to its children. This should work OOTB with the various components that this library provides (`<Input />`,`<Textarea /> for now) as they are just a collection of planes under the hood. So I would urge you to try the following:

```jsx
function MyXRInput(props) {
	const ref = React.useRef(null);

	function handleSelect(e) {
		ref.current.focus(); // focus the DOM element -> triggers the 3D element as well
	}

	function handleSelectMissed() {
		ref.current.blur(); // unfocus the DOM element -> also triggers 3D elem
	}

	return (
		<Interactive onSelect={handleSelect} onSelectMissed={handleSelectMissed}>
			<Input ref={ref} />
		</Interactive>
	)
}
```

I have never used `@react-three/xr`, nor do I have a headset/controllers to test this but I would assume it works the way I expect. Also note that I do not have an intuitive understanding of the events system in XR -- i.e. `onSelect` may or may not be what we want here. You probably know better than I about which events to bind, but the important part is that calling `ref.current.focus()` and `ref.current.blur()` when desired will get the functionality you desire.

Let me know how this works out, I'd love to know for future reference whether or not this is a proper solution! 😄

**Comment by laffan** [comment]
@JMBeresford finally got a chance to try this and it works perfectly!!  Thank you so much for your help.  I do think this is the currently the best/easiest solution for rendering in-headset editable text editor using RTF & the Meta Quest 2.

**Comment by JMBeresford** [comment]
Awesome, glad to hear it works out!
